server:
  type: simple
  applicationContextPath: /household
  connector:
    type: http
    port: 8080

database:
  driverClass: org.postgresql.Driver
  user: pg-user
  password: iAMs00perSecrEET
  url: jdbc:mysql://localhost:3306/Household
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
